/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface GeneScienceInterface extends ethers.utils.Interface {
  functions: {
    "getNewDNA(uint256)": FunctionFragment;
    "mergeDNA(uint32,uint32,uint32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getNewDNA",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mergeDNA",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getNewDNA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mergeDNA", data: BytesLike): Result;

  events: {};
}

export class GeneScience extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: GeneScienceInterface;

  functions: {
    getNewDNA(
      seed_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;

    mergeDNA(
      dna1: BigNumberish,
      dna2: BigNumberish,
      dna3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[number]>;
  };

  getNewDNA(seed_: BigNumberish, overrides?: CallOverrides): Promise<number>;

  mergeDNA(
    dna1: BigNumberish,
    dna2: BigNumberish,
    dna3: BigNumberish,
    overrides?: CallOverrides
  ): Promise<number>;

  callStatic: {
    getNewDNA(seed_: BigNumberish, overrides?: CallOverrides): Promise<number>;

    mergeDNA(
      dna1: BigNumberish,
      dna2: BigNumberish,
      dna3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<number>;
  };

  filters: {};

  estimateGas: {
    getNewDNA(
      seed_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mergeDNA(
      dna1: BigNumberish,
      dna2: BigNumberish,
      dna3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getNewDNA(
      seed_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mergeDNA(
      dna1: BigNumberish,
      dna2: BigNumberish,
      dna3: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
